### ISSUE TITLE
Error in Preprocess Text

### ISSUE THREAD

**Issue by ahmadalshammeri** [biolab/orange3-text#386]
##### Text version
0.5.0 < 0.5.2

##### Orange version
3.16.0

##### Issue

Hello, I'm using orange Canvas and once I drop the preprocess text I keep getting an error which I have tried using different PC but the same error keep popping up.

##### Additional info (worksheets, data, screenshots, ...)

![preprocess text error](https://user-images.githubusercontent.com/43742168/46288141-7e033480-c58d-11e8-93f6-c99123a91cce.JPG)

**Comment by ajdapretnar** [comment]
Please update Text add-on to the latest version - 0.5.2. This should resolve the issue.

**Comment by ahmadalshammeri** [comment]
Hello,


I have updated the Text add-on and I'm still having issue.

I still get the following error:


Exception:
LookupError: ********************************************************************** Resource 'corpora/stopwords' not found. Please use the NLTK Downloader to obtain the resource: >>> nltk.download() Searched in: - 'C:\\Users\\a.alshemari/nltk_data' - 'C:\\nltk_data' - 'D:\\nltk_data' - 'E:\\nltk_data' - 'C:\\Users\\a.alshemari\\AppData\\Local\\Orange\\nltk_data' - 'C:\\Users\\a.alshemari\\AppData\\Local\\Orange\\lib\\nltk_data' - 'C:\\Users\\a.alshemari\\AppData\\Roaming\\nltk_data' - 'C:\\Users\\a.alshemari\\AppData\\Roaming\\Orange\\nltk_data' **********************************************************************
Module:
nltk.data:653
Widget Name:
Preprocess Text
Widget Module:
orangecontrib.text.widgets.owpreprocess:629
Widget Scheme:
C:\Users\A32BA~1.ALS\AppData\Local\Temp\ows-600ljmy5.ows.xml
Version:
3.16.0
Environment:
Python 3.6.6 on Windows 10 10.0.16299 AMD64
Installed Packages:
AnyQt==0.0.8, Bottleneck==1.2.1, Orange3-Text==0.5.2, Orange3==3.16.0, PyJWT==1.6.4, PySocks==1.6.8, asn1crypto==0.24.0, atomicwrites==1.2.1, attrs==18.2.0, beautifulsoup4==4.6.3, biopython==1.72, blinker==1.4, boto3==1.9.14, boto==2.48.0, botocore==1.12.14, bz2file==0.98, certifi==2018.8.24, cffi==1.11.5, chardet==3.0.4, colorama==0.3.9, commonmark==0.8.1, cryptography-vectors==2.3.1, cryptography==2.3, cycler==0.10.0, decorator==4.3.0, docutils==0.14, docx2txt==0.7, future==0.16.0, gensim==3.5.0, idna==2.7, jmespath==0.9.3, joblib==0.12.3, keyring==9.0, keyrings.alt==3.1, kiwisolver==1.0.1, lxml==4.2.3, matplotlib==2.2.2, mkl-fft==1.0.4, mkl-random==1.0.1, more-itertools==4.3.0, networkx==2.1, nltk==3.2.4, numpy==1.13.3, oauthlib==2.1.0, odfpy==1.3.6, pdfminer3k==1.3.1, pip==10.0.1, pluggy==0.7.1, ply==3.11, py==1.6.0, pyOpenSSL==18.0.0, pycparser==2.18, pyparsing==2.2.0, pyqtgraph==0.10.0, pytest==3.8.1, python-dateutil==2.7.3, python-louvain==0.11, pytz==2018.5, pywin32==223, requests-oauthlib==1.0.0, requests==2.19.1, s3transfer==0.1.13, scikit-learn==0.19.1, scipy==0.19.1, serverfiles==0.2.1, setuptools-git==1.2, setuptools==40.2.0, simhash==1.9.0, six==1.11.0, smart-open==1.7.1, tornado==5.1, tweepy==3.6.0, typing==3.6.4, ufal.udpipe==1.2.0.1, urllib3==1.23, validate-email==1.3, wheel==0.31.1, wikipedia==1.4.0, win-inet-pton==1.0.1, wincertstore==0.2, xlrd==1.1.0
Machine ID:
176527414124981
Stack Trace:
Traceback (most recent call last):
  File "C:\Users\a.alshemari\AppData\Local\Orange\lib\site-packages\nltk\corpus\util.py", line 80, in __load
    try: root = nltk.data.find('{}/{}'.format(self.subdir, zip_name))
  File "C:\Users\a.alshemari\AppData\Local\Orange\lib\site-packages\nltk\data.py", line 653, in find
    raise LookupError(resource_not_found)
LookupError:
**********************************************************************
  Resource 'corpora/stopwords.zip/stopwords/' not found.  Please
  use the NLTK Downloader to obtain the resource:  >>>
  nltk.download()
  Searched in:
    - 'C:\\Users\\a.alshemari/nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
    - 'C:\\Users\\a.alshemari\\AppData\\Local\\Orange\\nltk_data'
    - 'C:\\Users\\a.alshemari\\AppData\\Local\\Orange\\lib\\nltk_data'
    - 'C:\\Users\\a.alshemari\\AppData\\Roaming\\nltk_data'
    - 'C:\\Users\\a.alshemari\\AppData\\Roaming\\Orange\\nltk_data'
**********************************************************************

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\a.alshemari\AppData\Local\Orange\lib\site-packages\Orange\canvas\scheme\widgetsscheme.py", line 573, in create_widget_instance
    widget.__init__()
  File "C:\Users\a.alshemari\AppData\Local\Orange\lib\site-packages\orangecontrib\text\widgets\owpreprocess.py", line 629, in __init__
    widget = stage(self)
  File "C:\Users\a.alshemari\AppData\Local\Orange\lib\site-packages\orangecontrib\text\widgets\owpreprocess.py", line 365, in __init__
    super().__init__(master)
  File "C:\Users\a.alshemari\AppData\Local\Orange\lib\site-packages\orangecontrib\text\widgets\owpreprocess.py", line 113, in __init__
    self.setup_method_layout()
  File "C:\Users\a.alshemari\AppData\Local\Orange\lib\site-packages\orangecontrib\text\widgets\owpreprocess.py", line 193, in setup_method_layout
    self.methods = [method() for method in self.methods]
  File "C:\Users\a.alshemari\AppData\Local\Orange\lib\site-packages\orangecontrib\text\widgets\owpreprocess.py", line 193, in <listcomp>
    self.methods = [method() for method in self.methods]
  File "C:\Users\a.alshemari\AppData\Local\Orange\lib\site-packages\orangecontrib\text\misc\nltk_data_download.py", line 55, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\a.alshemari\AppData\Local\Orange\lib\site-packages\orangecontrib\text\preprocess\filter.py", line 87, in __init__
    self.language = language
  File "C:\Users\a.alshemari\AppData\Local\Orange\lib\site-packages\orangecontrib\text\preprocess\filter.py", line 99, in language
    self.stopwords = set(stopwords.words(self.language.lower()))
  File "C:\Users\a.alshemari\AppData\Local\Orange\lib\site-packages\nltk\corpus\util.py", line 116, in __getattr__
    self.__load()
  File "C:\Users\a.alshemari\AppData\Local\Orange\lib\site-packages\nltk\corpus\util.py", line 81, in __load
    except LookupError: raise e
  File "C:\Users\a.alshemari\AppData\Local\Orange\lib\site-packages\nltk\corpus\util.py", line 78, in __load
    root = nltk.data.find('{}/{}'.format(self.subdir, self.__name))
  File "C:\Users\a.alshemari\AppData\Local\Orange\lib\site-packages\nltk\data.py", line 653, in find
    raise LookupError(resource_not_found)
LookupError:
**********************************************************************
  Resource 'corpora/stopwords' not found.  Please use the NLTK
  Downloader to obtain the resource:  >>> nltk.download()
  Searched in:
    - 'C:\\Users\\a.alshemari/nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
    - 'C:\\Users\\a.alshemari\\AppData\\Local\\Orange\\nltk_data'
    - 'C:\\Users\\a.alshemari\\AppData\\Local\\Orange\\lib\\nltk_data'
    - 'C:\\Users\\a.alshemari\\AppData\\Roaming\\nltk_data'
    - 'C:\\Users\\a.alshemari\\AppData\\Roaming\\Orange\\nltk_data'
**********************************************************************

Local Variables:
OrderedDict([('i', 1),
             ('m', <_sre.SRE_Match object; span=(0, 0), match=''>),
             ('modified_name', 'corpora/stopwords.zip/stopwords'),
             ('msg',
              "  Resource 'corpora/stopwords' not found.  Please use the NLTK\n"
              '  Downloader to obtain the resource:  >>> nltk.download()\n'
              '  Searched in:\n'
              "    - 'C:\\\\Users\\\\a.alshemari/nltk_data'\n"
              "    - 'C:\\\\nltk_data'\n"
              "    - 'D:\\\\nltk_data'\n"
              "    - 'E:\\\\nltk_data'\n"
              '    - '
              "'C:\\\\Users\\\\a.alshemari\\\\AppData\\\\Local\\\\Orange\\\\nltk_data'\n"
              '    - '
              "'C:\\\\Users\\\\a.alshemari\\\\AppData\\\\Local\\\\Orange\\\\lib\\\\nltk_data'\n"
              '    - '
              "'C:\\\\Users\\\\a.alshemari\\\\AppData\\\\Roaming\\\\nltk_data'\n"
              '    - '
              "'C:\\\\Users\\\\a.alshemari\\\\AppData\\\\Roaming\\\\Orange\\\\nltk_data'"),
             ('p',
              'C:\\Users\\a.alshemari\\AppData\\Roaming\\Orange\\nltk_data\\corpora\\stopwords'),
             ('path_',
              'C:\\Users\\a.alshemari\\AppData\\Roaming\\Orange\\nltk_data'),
             ('paths',
              ['C:\\Users\\a.alshemari/nltk_data',
               'C:\\nltk_data',
               'D:\\nltk_data',
               'E:\\nltk_data',
               'C:\\Users\\a.alshemari\\AppData\\Local\\Orange\\nltk_data',
               'C:\\Users\\a.alshemari\\AppData\\Local\\Orange\\lib\\nltk_data',
               'C:\\Users\\a.alshemari\\AppData\\Roaming\\nltk_data',
               'C:\\Users\\a.alshemari\\AppData\\Roaming\\Orange\\nltk_data']),
             ('pieces', ['corpora', 'stopwords']),
             ('resource_name', 'corpora/stopwords'),
             ('resource_not_found',
              '\n'
              '**********************************************************************\n'
              "  Resource 'corpora/stopwords' not found.  Please use the NLTK\n"
              '  Downloader to obtain the resource:  >>> nltk.download()\n'
              '  Searched in:\n'
              "    - 'C:\\\\Users\\\\a.alshemari/nltk_data'\n"
              "    - 'C:\\\\nltk_data'\n"
              "    - 'D:\\\\nltk_data'\n"
              "    - 'E:\\\\nltk_data'\n"
              '    - '
              "'C:\\\\Users\\\\a.alshemari\\\\AppData\\\\Local\\\\Orange\\\\nltk_data'\n"
              '    - '
              "'C:\\\\Users\\\\a.alshemari\\\\AppData\\\\Local\\\\Orange\\\\lib\\\\nltk_data'\n"
              '    - '
              "'C:\\\\Users\\\\a.alshemari\\\\AppData\\\\Roaming\\\\nltk_data'\n"
              '    - '
              "'C:\\\\Users\\\\a.alshemari\\\\AppData\\\\Roaming\\\\Orange\\\\nltk_data'\n"
              '**********************************************************************'),
             ('sep',
              '**********************************************************************'),
             ('zipentry', None),
             ('zipfile', None)])



________________________________

**Comment by ajdapretnar** [comment]
This looks like nltk_data wasn't downloaded at all. @robertcv Could you have a look at this? `'E:\\\\nltk_data'\n"` this seems very suspicious.

**Comment by robertcv** [comment]
Hey @ahmadalshammeri ! Could you please provide us with some additional information. The problem seems to be that some files that are normally downloaded in the background and saved to your disc are missing. Are on the beforementioned PCs any read/write restrictions enforced? Are you connected to the internet and are there any restrictions?

**Comment by ajdapretnar** [comment]
Closed due to inactivity.

**Comment by luanSaid** [comment]
I have the same issue

**Comment by ariethic** [comment]
> I have the same issue

me too

**Comment by ajdapretnar** [comment]
Ok @ariethic, please help me pinpoint the problem. Are you behind a proxy? On a work computer without admin privileges? Anything of the sort?
