### ISSUE TITLE
Twitter api access problem

### ISSUE THREAD

**Issue by nomad101** [biolab/orange3-text#772]
**Describe the bug**
I'm new to Orange3. I downloade the Twitter Data Analysis workflow, and followed theh prompt to install add-in.
Cannot use the Twitter addon.

**To Reproduce**
1. Twiiter Orange - added in API key details
2. Tried the default search
4. See: API 403 Forbidden. 453 - You currently have Essential access which includes access to Twitter API v2 endpoints only. If you need access to this endpoint, you’ll need to apply for Elevated access via the Developer Portal.

Is this correct. As in the Video tutorial link it does not mention needing 'Elevated access'?

**Operating system:**
Windows 10

Thanks

**Comment by wvdvegte** [comment]
You need to use an old Twittter account with access to the v1 Twitter API. Orange does not (yet) support the current v2 Twitter API. See [this post](https://discord.com/channels/633376992607076354/633376994595438609/914910840501714964) on Discord.

**Comment by ajdapretnar** [comment]
Fixed in #780

**Comment by SmartRu** [comment]
I got the latest bearer token according to the tutorial, but when I try to use it in orange it still shows 403 forbidden.


Current environment windows10 text -v1.8
tutorial twitter  : [https://developer.twitter.com/en/docs/authentication/oauth-2-0/bearer-tokens](url)

**Comment by ajdapretnar** [comment]
Did you turn on user authentication settings?
