### ISSUE TITLE
Topic Modeling Crash

### ISSUE THREAD

**Issue by layudhi** [biolab/orange3-text#820]
**What's wrong?**

Topic Modeling Crash when used with Twitter Widget

**How can we reproduce the problem?** 

Please see the Screen Shoot, i cannot save the owl with Topic Modeling connected since the App will freeze and then Not Responding after connecting the Widget from Corpus

**What's your environment?**

- Operating system: Windows 10 64Bit
- Orange version: 3.32
- How you installed Orange: 

1. By clinking the standalone installation files.
2. Installation Folder Orange: C:\Program Files\Orange
3. Installation miconda3 : C:\Users\ASUS\miniconda3
![Screenshot 2022-04-19 165813](https://user-images.githubusercontent.com/102269946/163969660-00cd0c8d-30a9-4e13-a313-79946e0c3457.png)
![Screenshot 2022-04-19 170110](https://user-images.githubusercontent.com/102269946/163969671-ab4bc8c6-d87f-4e05-a7fc-c2bb8f441c23.png)

**Comment by ajdapretnar** [comment]
I've collated all the reports of the same kind. Two other uses say Topic Modelling crashes on Windows (doesn't happen on Mac). One user doesn't even have a large corpus (174 documents and 909 tokens).

We need to research why this happens. @noahnovsak @PrimozGodec

**Comment by NAsic123** [comment]
I have the same problem - Topic Modelling crushes when I want to run it.

**Comment by PrabodhaCha** [comment]
I have the same issue, this is on windows. 
It crashes even with 100 tweets
![image](https://user-images.githubusercontent.com/91814994/175789832-837ed602-4bd3-4eba-87a9-2aea9b35aafc.png)

**Comment by nadiaelen** [comment]
> I've collated all the reports of the same kind. Two other uses say Topic Modelling crashes on Windows (doesn't happen on Mac). One user doesn't even have a large corpus (174 documents and 909 tokens).
> 
> We need to research why this happens. @noahnovsak @PrimozGodec

Hi, any news on this? Thanks...

**Comment by ajdapretnar** [comment]
We just released Orange3-Text v. 1.10.0. Please update the add-on and let us know if it works.

If not, we would appreciate if you could provide a workflow, data sample (if possible) and the pip freeze output, if you installed Orange via the terminal.

**Comment by NAsic123** [comment]
@ajdapretnar I updated add-on and it still crushes. I am sending additional information bellow. 

What's your environment/workflow?
- processor Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz   1.50 GHz
- installed memory RAM	8,00 GB (uporabno 7,80 GB)
- system 64-bitni operacijski sistem, procesor x64
- Windows Windows 11 Home, version 21H2

- Orange version: 3.32.0

How you installed Orange:

- By clinking: https://orangedatamining.com/

My data sample is here.[](url)
[kurent_neprecisceno.xlsx](https://github.com/biolab/orange3-text/files/9071378/kurent_neprecisceno.xlsx)

Pip freeze output:
When I run Topic Modelling it is like this for a few minutes:
![image](https://user-images.githubusercontent.com/108016235/177977714-cee2f35e-6e25-4ad4-a93f-3fce1f7392ff.png)

And then it is like:
![image](https://user-images.githubusercontent.com/108016235/177977740-95b83262-fde3-4730-bb98-f61111c65880.png)

And then it says:
![image](https://user-images.githubusercontent.com/108016235/177977784-65cbe74a-c084-4a29-af72-e3407af0b1e8.png)

**Comment by ajdapretnar** [comment]
@NAsic123 What happens it you select to wait?

**Comment by ajdapretnar** [comment]
Also, I tried it on Mac with your data. I am assuming you are using the default preprocessing and LDA? It works normally for me.
@djukicn Any ideas? Could it be a Windows issue?

**Comment by ajdapretnar** [comment]
Two comments, unrelated to the crashing widget. In preprocess, you don't need Regexp, because tokenization you've set already omits all punctuation. Also, your POS tag filter doesn't do anything, because your data is not tagged, so filtering cannot work.

**Comment by NAsic123** [comment]
@ajdapretnar  thank you. I will correct it.

And I let the LDA run for one hour and it was still on 0 % and then it crushed.

**Comment by ajdapretnar** [comment]
@NAsic123 Sorry, this was a bit technical. I would be wary of tampering with the set up environment.
However, there is a special program called Orange Command Prompt, which you can find from the start menu. Open it and first run `pip freeze` and post the output here. This will help us identify which version of the gensim library you currently have. Then we can proceed with carefully downgrading and then upgrading again.

**Comment by NAsic123** [comment]
@ajdapretnar thank you for your instruction. I ran pip freeze and got this information below (I copied and saved it in .txt). I hope it is useful and thank you again.
[](url
[pip freeze.txt](https://github.com/biolab/orange3-text/files/9081688/pip.freeze.txt)
)

**Comment by ajdapretnar** [comment]
Ok, it does indeed seem like you have `gensim==4.2.0`.
Now please try running `pip install gensim==4.1.2`.
Then open Orange and see it Text works. Please, let me know.

**Comment by NAsic123** [comment]
Thank you, I installed it and now it works, Topic Modelling does not crash.
But I get this notification (**_init_()_, got un unexpected keyword argument 'random_seed'**).  Is it maybe that I insert wrong Preprocessing settings?
![image](https://user-images.githubusercontent.com/108016235/178212819-52c6d2ad-9c95-4321-9d0f-515f47cdadbb.png)

My Preprocessing settings:
![image](https://user-images.githubusercontent.com/108016235/178213305-394a9974-3313-41ff-b9d2-b5a6bc050509.png)

**Comment by ajdapretnar** [comment]
@NAsic123 No, your preprocessing is fine. This one needs to be solved by the core team.

@djukicn It seems like `gensim==4.1.2` works. But LSI model has the new `random_seed` parameter added in version 4.2.0. Do you perhaps have an idea what causes gensim 4.2.0 to no work on Windows?

**Comment by NAsic123** [comment]
@ajdapretnar thank you. I ran LDA and now it works. I get the results so not it works. Thank you so much for help.
But also with the LDA, I get the same message with random_seed.
![image](https://user-images.githubusercontent.com/108016235/178217073-6f9b995c-7ac7-4ced-a762-ee9dadb6f8ea.png)

**Comment by djukicn** [comment]
@ajdapretnar I was actually able reproduce the error (although to me the results were produced after clicking "Wait" a few times) on Ubuntu so it's not just a Windows issue. Somewhere in the background gensim raises an exception. I'll look into it today and see what can be done.

**Comment by ajdapretnar** [comment]
@djukicn Fantastic! Thanks!

**Comment by ajdapretnar** [comment]
@nadiaelen We haven't been able to identify the real culprit. Once we do, we will prepare the fix and link it to this thread.

**Comment by nadiaelen** [comment]
> @nadiaelen We haven't been able to identify the real culprit. Once we do, we will prepare the fix and link it to this thread.

any news? I am stuck for two months, I would really appreciate some help. Thank you.

**Comment by ajdapretnar** [comment]
@nadiaelen Unfortunately, no progress so far. We simply cannot consistently reproduce the issue on any machine. Once the update comes, it will be posted in the thread.

**Comment by nadiaelen** [comment]
any news?

**Comment by PrimozGodec** [comment]
We have reported the issue to Gensim (the library which computes topics), hope they will consider it soon https://github.com/RaRe-Technologies/gensim/issues/3368

**Comment by ajdapretnar** [comment]
@nadiaelen If you are on Windows, you could try opening Orange Command Prompt (a separate program available from Start menu). Then enter `pip install gensim==4.1.2`. Hopefully, this will solve the issue. It's the best I can give at the moment.

**Comment by Katzengurke** [comment]
Hey, I tried source installation with the merged files from #885 (newest biolab repository), but it didnt work. Orange still crashes. I also tried different versions of orange3 with older add-on versions, didnt work either. 
Im using Windows 11. Any idea how to fix it?

**Comment by ajdapretnar** [comment]
@Katzengurke When you say Orange crashes, do you mean the software or the topic modelling widget?
Could you perhaps open Orange Command Prompt, run `python -m Orange.canvas` and try the workflow that results in a crash? Then copy and paste the log here, please.

**Comment by Katzengurke** [comment]
The software crashes. 
I tried running the command prompt, but I only get the message "Python stopped working".

**Comment by ajdapretnar** [comment]
> Tried the same on a windows 10 laptop where I didnt temper with any files whatsoever, and it works there. Is it maybe Windows 11?

It might be. Does it happen even if you uninstall orange3-text add-on?

**Comment by ajdapretnar** [comment]
Can you try running `python` in Orange Command Prompt and let me know the Python version it reports? I'll check if any known Python+Win11 bugs exist.

**Comment by Katzengurke** [comment]
> > Tried the same on a windows 10 laptop where I didnt temper with any files whatsoever, and it works there. Is it maybe Windows 11?
> 
> It might be. Does it happen even if you uninstall orange3-text add-on?

Yes, sadly. Ill uninstall my Python, my Anaconda and Orange, and then try again with a new installation, and let you know in a couple of minutes. 


> Can you try running `python` in Orange Command Prompt and let me know the Python version it reports? I'll check if any known Python+Win11 bugs exist.

Same with that.

**Comment by ajdapretnar** [comment]
Ok, so it is a Python bug not an Orange bug.

Does running `python --version` work?

**Comment by Katzengurke** [comment]
Alright, I got a bit farther, but the bug got stranger too. 
I uninstalled everything like I said, and reinstalled Orange 3.32 and text from source. Afterwards I tried connecting a corpus widget to topic modelling, but Python stopped working again. I went for python -m Orange.canvas in order to get the log, but the stopped working again, and changed my resolution settings.

Python is 3.8.8

**Comment by nadiaelen** [comment]
So, the same thing remains: even with the new gensim library, it runs into the same problem, it just hangs forever, after all install, deinstall, etc...:(

**Comment by Katzengurke** [comment]
> So, the same thing remains: even with the new gensim library, it runs into the same problem, it just hangs forever, after all install, deinstall, etc...:(

The fix #885 definitely works under Windows 10, I was able to install it and work with it, without crashes so far. You have to use the source installation with git and the orange command prompt. Doesnt work with my Windows 11 laptop though.

**Comment by JosieVor** [comment]
Hey, 

 I am using orange data mining for my master thesis. However, when I try topic modelling, it crashes. I already read this thread but it was a bit too technical for me to understand since I really do not have any experience with Orange or Python. Can someone help me out?

My environment: Windows 11 Home 64Bit

**Comment by nadiaelen** [comment]
I really love Orange and appreciate you, your work and everything, but, truly, when it comes to topic modelling, which is the hottest topic right now, one weeks works, one week crashes and stays like that for a month...

**Comment by PrimozGodec** [comment]
@JosieVor and @nadiaelen, sorry for the late response. I tried to reproduce the error on MacOS and Windows, and it works for me. Can you please give me more information so I can dig deeper into the problem?

- @nadiaelen, do you also use Windows?
- Can you prepare a workflow which crashes? What dataset do you use?
- Which Topic modelling model causes the crash?
- What is the version of the Text add-on that you use? You can see the version if you go under Options>Add-ons and see the currently installed version in the list.
- What version of the Orange do you have? You can find the version on Windows under the Help>About menu.
- What is the version of the Gensim library? You can get it if you open the Orange command prompt (click the Start button on Windows and then start typing the Orange command prompt). Type `pip freeze` in the command prompt and then press enter. Scroll through the list and find Gensim.

Thank you in advance.

**Comment by JosieVor** [comment]
I am using a Twitter Dataset, which I scrapped directly on Orange. My dataset is quite big (about 30.000 Tweets) but I also have tried topic modeling on smaller datasets (about 100 Tweets, and it still did not work).

I am using LDA, which crashes every time. LSI sometimes works, but more often than not it does not work, either. 

Text Add-On Version: 1.12.0

Orange Version: 3.34.0
 
Gensim Version: the pip freeze command does not work for me, but when I use pip list, it says my version is 4.1.2

**Comment by calliope212** [comment]
Hi, I'm using windows 10 and also have the same issues. I already tried the pip freeze using orange command but it still crashed. I also tried to reinstall but still have the same result. Is there any other solution?

Orange version: 3.34.0
Text Add-On version: 1.12.1
Gensim: 4.1.2

**Comment by PrimozGodec** [comment]
Thank you @JosieVor and @calliope212, for the additional information.  We noticed that the newest release didn't support using genim>=4.3.0 (on the master branch we already switched to >=4.3.0).

We fixed the release. Can you please update the Text addon to version 1.12.2 and try again? Please let us know if it helps.

**Comment by calliope212** [comment]
Thank you @PrimozGodec for the suggestion. I tried it but unfortunately, it still won't work. When I check the pip list, it says my gensim version is 4.3.1. Is that affect the result?

**Comment by sohbl** [comment]
Hi, I also have similar issues when I run Topic Modelling, it hangs for more than 2 minutes and I have to kill it ultimately. 
I'm running on Windows **11**. 
Orange version = 3.34.0
Text Add-on version = 1.13.1
Gensim version = **4.3.0**

Another laptop has the same problem. It is running on Windows **10**. 
Orange version = 3.34.0
Text Add-on version = 1.13.1
Gensim version = **4.3.1**

Is there any solution for this problem?

**Comment by IzaClaro** [comment]
Hi!
I am also having this problem, whenever I run Topic Modelling widget, the program crashes and ultimatly I have to force shutdown on my computer, as it seems everything fails after!
I am running windows 11 as well.

Orange version 3.35
Gensim version = 4.3.0

Do you already have any solution for this problem?
Thanks.

**Comment by PrimozGodec** [comment]
The new version of Gensim (4.3.2) is out. Can you try with this version? We still cannot reproduce the bug on the new or previous version.
How do I upgrade to a new Gensim (select any of the following options)?
- Open Orange Command Prompt from the start menu and write `conda update gensim orange3-text` (Windows only)
- Open the Addons dialogue in Orange, click Add more and type Gensim. Check gensim at the bottom of the list. Also, check orange3-text to be upgraded (if not yet).

**Comment by ajdapretnar** [comment]
I am closing this as stale. If the error persists, please open a new issue.

**Comment by Bragheto** [comment]
2024 and the error persist. If preprocess uses n_gram range, it crashes.

**Comment by Bragheto** [comment]
> Is this still a Windows issue? Because I ran grimm-tales with n-grams and TM worked. I have the latest gensim installed (gensim==4.3.2).
![image](https://github.com/biolab/orange3-text/assets/25119641/5b247310-1534-4df4-bad8-63cb4177c6ec)
Same here.
Yes, I am using the GUI in Windows 11 (Compilation 22631.3447 and Windows Feature Experience Pack 1000.22688.1000.0).

As soon as I disabled n_gram range in the preprocess workflow, everything worked.
